/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppAgainButton {
        "dogSelected": string;
        "handleClick": (e: Event) => void;
    }
    interface AppHome {
    }
    interface AppImage {
        "altText": string;
        "dogImage": string;
    }
    interface AppOnLoad {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppSelectMenu {
        "handleChange": (e: Event) => void;
    }
    interface AppShareSocial {
        "dogName": string;
        "handleFbClick": (e: Event) => void;
        "handleTwClick": (e: Event) => void;
        "imageUrl": string;
    }
}
declare global {
    interface HTMLAppAgainButtonElement extends Components.AppAgainButton, HTMLStencilElement {
    }
    var HTMLAppAgainButtonElement: {
        prototype: HTMLAppAgainButtonElement;
        new (): HTMLAppAgainButtonElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppImageElement extends Components.AppImage, HTMLStencilElement {
    }
    var HTMLAppImageElement: {
        prototype: HTMLAppImageElement;
        new (): HTMLAppImageElement;
    };
    interface HTMLAppOnLoadElement extends Components.AppOnLoad, HTMLStencilElement {
    }
    var HTMLAppOnLoadElement: {
        prototype: HTMLAppOnLoadElement;
        new (): HTMLAppOnLoadElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSelectMenuElement extends Components.AppSelectMenu, HTMLStencilElement {
    }
    var HTMLAppSelectMenuElement: {
        prototype: HTMLAppSelectMenuElement;
        new (): HTMLAppSelectMenuElement;
    };
    interface HTMLAppShareSocialElement extends Components.AppShareSocial, HTMLStencilElement {
    }
    var HTMLAppShareSocialElement: {
        prototype: HTMLAppShareSocialElement;
        new (): HTMLAppShareSocialElement;
    };
    interface HTMLElementTagNameMap {
        "app-again-button": HTMLAppAgainButtonElement;
        "app-home": HTMLAppHomeElement;
        "app-image": HTMLAppImageElement;
        "app-on-load": HTMLAppOnLoadElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-select-menu": HTMLAppSelectMenuElement;
        "app-share-social": HTMLAppShareSocialElement;
    }
}
declare namespace LocalJSX {
    interface AppAgainButton {
        "dogSelected"?: string;
        "handleClick"?: (e: Event) => void;
    }
    interface AppHome {
    }
    interface AppImage {
        "altText"?: string;
        "dogImage"?: string;
    }
    interface AppOnLoad {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppSelectMenu {
        "handleChange"?: (e: Event) => void;
    }
    interface AppShareSocial {
        "dogName"?: string;
        "handleFbClick"?: (e: Event) => void;
        "handleTwClick"?: (e: Event) => void;
        "imageUrl"?: string;
    }
    interface IntrinsicElements {
        "app-again-button": AppAgainButton;
        "app-home": AppHome;
        "app-image": AppImage;
        "app-on-load": AppOnLoad;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-select-menu": AppSelectMenu;
        "app-share-social": AppShareSocial;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-again-button": LocalJSX.AppAgainButton & JSXBase.HTMLAttributes<HTMLAppAgainButtonElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-image": LocalJSX.AppImage & JSXBase.HTMLAttributes<HTMLAppImageElement>;
            "app-on-load": LocalJSX.AppOnLoad & JSXBase.HTMLAttributes<HTMLAppOnLoadElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-select-menu": LocalJSX.AppSelectMenu & JSXBase.HTMLAttributes<HTMLAppSelectMenuElement>;
            "app-share-social": LocalJSX.AppShareSocial & JSXBase.HTMLAttributes<HTMLAppShareSocialElement>;
        }
    }
}
