/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppAgainButton {
        "dogSelected": string;
        "handleClick": (e: Event) => void;
    }
    interface AppHome {
    }
    interface AppImage {
        "dogImage": string;
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppSelectMenu {
        "handleChange": (e: Event) => void;
    }
}
declare global {
    interface HTMLAppAgainButtonElement extends Components.AppAgainButton, HTMLStencilElement {
    }
    var HTMLAppAgainButtonElement: {
        prototype: HTMLAppAgainButtonElement;
        new (): HTMLAppAgainButtonElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppImageElement extends Components.AppImage, HTMLStencilElement {
    }
    var HTMLAppImageElement: {
        prototype: HTMLAppImageElement;
        new (): HTMLAppImageElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSelectMenuElement extends Components.AppSelectMenu, HTMLStencilElement {
    }
    var HTMLAppSelectMenuElement: {
        prototype: HTMLAppSelectMenuElement;
        new (): HTMLAppSelectMenuElement;
    };
    interface HTMLElementTagNameMap {
        "app-again-button": HTMLAppAgainButtonElement;
        "app-home": HTMLAppHomeElement;
        "app-image": HTMLAppImageElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-select-menu": HTMLAppSelectMenuElement;
    }
}
declare namespace LocalJSX {
    interface AppAgainButton {
        "dogSelected"?: string;
        "handleClick"?: (e: Event) => void;
    }
    interface AppHome {
    }
    interface AppImage {
        "dogImage"?: string;
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppSelectMenu {
        "handleChange"?: (e: Event) => void;
    }
    interface IntrinsicElements {
        "app-again-button": AppAgainButton;
        "app-home": AppHome;
        "app-image": AppImage;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-select-menu": AppSelectMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-again-button": LocalJSX.AppAgainButton & JSXBase.HTMLAttributes<HTMLAppAgainButtonElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-image": LocalJSX.AppImage & JSXBase.HTMLAttributes<HTMLAppImageElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-select-menu": LocalJSX.AppSelectMenu & JSXBase.HTMLAttributes<HTMLAppSelectMenuElement>;
        }
    }
}
